### PR TITLE
register mobile config

### PR DESCRIPTION
**Pull request by sslotsky**
There are some text editor issues here (tabs vs. spaces).

This PR addresses https://github.com/Jabbslad/accounts-github/issues/3 and is currently untested. Hoping to start conversation around the proposed change.

### CODE REVIEW

**Comment by sslotsky** [comment]
Tried testing my local package and this does not work. There is an ```accounts-github.js``` file that winds up in the package directory. I plead ignorance as to how it gets there, but the important part is that my mobile specific logic doesn't exist there.

**Comment by Jabbslad** [comment]
Hi @sslotsky, thanks for the PR...

My memory around this Github Login Service is quite hazy, if I remember correctly I developed it three years ago when Meteor was experimenting with authentication in a separate "auth" branch. Based on #2 I would hazard a guess that my code is fundamentally broken due to Meteor making breaking changes. I was going to resolve them but I'm sure that Meteor rolled in their own Github auth package or something to that effect, thus superseding my early attempt: https://www.meteor.com/accounts and https://atmospherejs.com/meteor/accounts-github

If the official package doesnt do what you require and you are able to take this project forwards I'm more than willing to transfer repo ownership to you.

**Comment by sslotsky** [comment]
@Jabbslad sorry - I thought your repo *was* the official repo! The atmosphere page doesn't list one and yours is the first to come up when I google it. If you know where the repo is for the official package I'll just file the issue there instead. Thanks for your reply!

**Comment by Jabbslad** [comment]
@sslotsky it looks like the package is bundled into the meteor repo here: https://github.com/meteor/meteor/tree/devel/packages/accounts-github

**Pull request closed without merging**
